export const EXECUTIVE_SPONSOR_OPTIONS = [
  'CEO',
  'CFO',
  'COO',
];

export const TARGET_START_QUARTER_OPTIONS = [
  'Q2 2026',
  'Q3 2026',
  'Q4 2026',
  'Q1 2027',
];

export const PROJECT_CATEGORY_OPTIONS = [
  'Safety',
  'Growth',
  'Efficiency',
  'Compliance',
];

export const CURRENT_PROJECT_CLASSIFICATION_OPTIONS = [
  'Major project',
  'Operational project',
];

export const SEEDED_OPERATIONAL_INITIATIVES = [
  {
    id: 'AOI-2026-01',
    title: 'Build organizational alignment around the Theory of Change',
    year: 2026,
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Create sustainable program impact',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Align programs, measures, and reporting to a shared Theory of Change framework.',
  },
  {
    id: 'AOI-2026-02',
    title: 'Establish Pioneer as the leading diversion provider in priority regions',
    year: 2026,
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Create sustainable program impact',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Expand diversion services in priority regions through launch planning and market development.',
  },
  {
    id: 'AOI-2026-03',
    title: 'Strengthen and scale Pioneer\'s reentry service model',
    year: 2026,
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Create sustainable program impact',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Strengthen reentry programming and broaden adoption of the service model.',
  },
  {
    id: 'AOI-2026-04',
    title: 'Ensure Pioneer can attract and retain the talent needed to support growth',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Improve recruiting pipelines and retention practices to support planned growth.',
  },
  {
    id: 'AOI-2026-05',
    title: 'Ensure the organization has the leadership capacity to sustain long-term growth',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Build leadership depth and succession plans needed for long-term expansion.',
  },
  {
    id: 'AOI-2026-06',
    title: 'Ensure equity is reflected in how Pioneer recruits, develops and advances talent',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Advance equitable hiring, development, and promotion outcomes across the organization.',
  },
  {
    id: 'AOI-2026-07',
    title: 'Shift HR capacity toward higher-value strategic work',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Reduce low-value HR work and shift capacity toward strategic workforce support.',
  },
  {
    id: 'AOI-2026-08',
    title: 'Strengthen the scale and diversification of Pioneer Industries',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Grow and diversify Pioneer Industries through new customers, investments, and marketing.',
  },
  {
    id: 'AOI-2026-09',
    title: 'Expand and diversify our food services enterprise',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Expand food services offerings and define a sustainable path for future growth.',
  },
  {
    id: 'AOI-2026-10',
    title: 'Strengthen financial sustainability across program operations',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Improve revenue diversity and strengthen the financial model of program operations.',
  },
  {
    id: 'AOI-2026-11',
    title: 'Optimize building assets to support mission and financial performance',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Plan building and real-estate use to better support mission delivery and financial performance.',
  },
  {
    id: 'AOI-2026-12',
    title: 'Identify and advance new mission-aligned enterprise opportunities',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Identify and evaluate new enterprise opportunities that align with mission and capacity.',
  },
  {
    id: 'AOI-2026-13',
    title: 'Establish a structured process for capturing and evaluating new ideas',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Create a repeatable process for collecting, reviewing, and advancing new ideas.',
  },
  {
    id: 'AOI-2026-14',
    title: 'Test a transitional jobs model in landscaping services',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Pilot a landscaping-based transitional jobs model and assess expansion potential.',
  },
  {
    id: 'AOI-2026-15',
    title: 'Strengthen technology infrastructure, security and collaboration across the organization',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Upgrade core technology, security, and collaboration capabilities across the organization.',
  },
  {
    id: 'AOI-2026-16',
    title: 'Expand housing access for justice-involved individuals',
    year: 2026,
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Advance fair chance housing efforts for justice-involved individuals through advocacy and partnership.',
  },
  {
    id: 'AOI-2026-17',
    title: 'Ensure continuity of healthcare coverage for justice-involved populations',
    year: 2026,
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Protect continuity of healthcare coverage for justice-involved populations.',
  },
  {
    id: 'AOI-2026-18',
    title: 'Advance policy reforms that reduce unnecessary incarceration',
    year: 2026,
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Develop reforms that reduce unnecessary incarceration and support system change.',
  },
  {
    id: 'AOI-2026-19',
    title: 'Elevate visibility of Pioneer\'s impact',
    year: 2026,
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Increase visibility of Pioneer’s outcomes and impact through reporting and outreach.',
  },
];

export const SEEDED_STRATEGIC_PRIORITY_PERIODS = [
  {
    id: 'SPP-2024-2029',
    label: 'Strategic Priorities 2024-2029',
    approvedOn: '2026-04-12',
    startYear: 2024,
    endYear: 2029,
    status: 'active',
    priorities: [
      {
        id: 'SP-201',
        title: 'Create sustainable program impact',
        description: '',
      },
      {
        id: 'SP-202',
        title: 'Prioritize employee well-being',
        description: '',
      },
      {
        id: 'SP-203',
        title: 'Build strong financial resilience',
        description: '',
      },
      {
        id: 'SP-204',
        title: 'Build a supportive ecosystem that fosters innovation',
        description: '',
      },
      {
        id: 'SP-205',
        title: 'Champion systemic changes within the criminal justice system',
        description: '',
      },
    ],
  },
];
