export const EXECUTIVE_SPONSOR_OPTIONS = [
  'CEO',
  'CFO',
  'COO',
];

export const TARGET_START_QUARTER_OPTIONS = [
  'Q2 2026',
  'Q3 2026',
  'Q4 2026',
  'Q1 2027',
];

export const PROJECT_CATEGORY_OPTIONS = [
  'Safety',
  'Growth',
  'Efficiency',
  'Compliance',
];

export const CURRENT_PROJECT_CLASSIFICATION_OPTIONS = [
  'Major project',
  'Operational project',
];

export const SEEDED_OPERATIONAL_INITIATIVES = [
  {
    id: 'AOI-2026-01',
    title: 'FY2026 Access Throughput Plan',
    year: 2026,
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Improve patient access',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Annual operating initiatives focused on intake, scheduling capacity, and patient self-service adoption.',
  },
  {
    id: 'AOI-2026-02',
    title: 'FY2026 Access Capacity Management',
    year: 2026,
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Improve patient access',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Improve clinic template management, referral throughput, and provider capacity utilization.',
  },
  {
    id: 'AOI-2026-03',
    title: 'FY2026 Digital Intake Adoption',
    year: 2026,
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Improve patient access',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Drive digital intake completion, self-scheduling uptake, and reduced front-desk friction.',
  },
  {
    id: 'AOI-2026-04',
    title: 'FY2026 Margin Performance Plan',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Strengthen operating margin',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Annual operating initiatives focused on productivity, labor management, and cost discipline.',
  },
  {
    id: 'AOI-2026-05',
    title: 'FY2026 Workforce Productivity Improvement',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Strengthen operating margin',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Target staffing model performance, premium labor reduction, and manager accountability.',
  },
  {
    id: 'AOI-2026-06',
    title: 'FY2026 Supply Cost Discipline',
    year: 2026,
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Strengthen operating margin',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Reduce avoidable supply variance and improve sourcing, inventory visibility, and controls.',
  },
  {
    id: 'AOI-2026-07',
    title: 'FY2026 Platform Resilience Plan',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Modernize core platforms',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Annual operating initiatives focused on core platform hardening, data modernization, and resilience.',
  },
  {
    id: 'AOI-2026-08',
    title: 'FY2026 Enterprise Data Foundation',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Modernize core platforms',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Strengthen enterprise data pipelines, governance, and shared platform capabilities.',
  },
  {
    id: 'AOI-2026-09',
    title: 'FY2026 Core Application Lifecycle',
    year: 2026,
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Modernize core platforms',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Advance lifecycle refresh planning, dependency remediation, and service resilience.',
  },
  {
    id: 'AOI-2026-10',
    title: 'FY2026 Compliance Readiness Plan',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Reduce regulatory risk',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Annual operating initiatives focused on policy adherence, controls, and audit readiness.',
  },
  {
    id: 'AOI-2026-11',
    title: 'FY2026 Audit Controls Sustainment',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Reduce regulatory risk',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Improve evidence capture, control ownership, and internal audit issue closure discipline.',
  },
  {
    id: 'AOI-2026-12',
    title: 'FY2026 Policy Compliance Monitoring',
    year: 2026,
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Reduce regulatory risk',
    strategicPriorityPeriodId: 'SPP-2026',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2026-2030',
    description: 'Improve operational policy adherence monitoring, escalation, and remediation workflows.',
  },
];

export const SEEDED_STRATEGIC_PRIORITY_PERIODS = [
  {
    id: 'SPP-2025',
    label: 'Strategic Priorities 2025-2025',
    approvedOn: '2025-03-01',
    startYear: 2025,
    endYear: 2025,
    status: 'archived',
    priorities: [
      {
        id: 'SP-101',
        title: 'Expand ambulatory access',
        description: 'Increase visit capacity and improve referral-to-appointment conversion.',
      },
      {
        id: 'SP-102',
        title: 'Stabilize labor productivity',
        description: 'Improve staffing efficiency and reduce contract labor dependence.',
      },
      {
        id: 'SP-103',
        title: 'Improve cybersecurity posture',
        description: 'Strengthen access controls, resilience testing, and incident preparedness.',
      },
    ],
  },
  {
    id: 'SPP-2026',
    label: 'Strategic Priorities 2026-2030',
    approvedOn: '2026-03-01',
    startYear: 2026,
    endYear: 2030,
    status: 'active',
    priorities: [
      {
        id: 'SP-201',
        title: 'Improve patient access',
        description: 'Reduce scheduling friction, speed intake, and improve self-service access to care.',
      },
      {
        id: 'SP-202',
        title: 'Strengthen operating margin',
        description: 'Target cost discipline, productivity gains, and measurable financial improvement.',
      },
      {
        id: 'SP-203',
        title: 'Modernize core platforms',
        description: 'Upgrade foundational technology, resilience, and enterprise data capabilities.',
      },
      {
        id: 'SP-204',
        title: 'Reduce regulatory risk',
        description: 'Advance compliance readiness, auditability, and policy adherence across operations.',
      },
    ],
  },
];
