export const EXECUTIVE_SPONSOR_OPTIONS = [
  'CEO',
  'CFO',
  'COO',
];

export const TARGET_START_QUARTER_OPTIONS = [
  'Q2 2026',
  'Q3 2026',
  'Q4 2026',
  'Q1 2027',
];

export const PROJECT_CATEGORY_OPTIONS = [
  'Safety',
  'Growth',
  'Efficiency',
  'Compliance',
];

export const CURRENT_PROJECT_CLASSIFICATION_OPTIONS = [
  'Major project',
  'Operational project',
];

export const SEEDED_OPERATIONAL_INITIATIVES = [
  {
    id: '2026.1.1',
    title: 'Build organizational alignment around the Theory of Change',
    year: 2026,
    owner: 'Hilary',
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Create sustainable program impact',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Align programs, measures, and reporting to a shared Theory of Change framework.',
  },
  {
    id: '2026.1.2',
    title: 'Establish Pioneer as the leading diversion provider in priority regions',
    year: 2026,
    owner: 'Clint',
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Create sustainable program impact',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Expand diversion services in priority regions through launch planning and market development.',
    milestones: [
      {
        id: 'AOI-2026.1.2-MS-1',
        title: 'Regional expansion roadmap approved',
        description: 'Confirm target counties, launch criteria, and partner sequencing for the diversion expansion plan.',
        plannedDate: '2026-01-31',
        originalPlannedDate: '2026-01-31',
        actualDate: '2026-01-29',
      },
      {
        id: 'AOI-2026.1.2-MS-2',
        title: 'Partner MOUs and referral model aligned',
        description: 'Complete core partner alignment on referral volumes, operating model, and intake responsibilities.',
        plannedDate: '2026-02-28',
        originalPlannedDate: '2026-02-28',
        actualDate: '',
      },
      {
        id: 'AOI-2026.1.2-MS-3',
        title: 'Launch readiness review complete',
        description: 'Validate staffing, training, reporting, and site readiness before the first regional go-live.',
        plannedDate: '2026-03-31',
        originalPlannedDate: '2026-03-31',
        actualDate: '',
      },
    ],
    monthlyProgressUpdates: [
      {
        id: 'AOI-2026.1.2-UPD-2026-01',
        month: '2026-01',
        createdAt: '2026-01-31',
        scopeStatus: 'green',
        scheduleStatus: 'green',
        costStatus: 'green',
        riskStatus: 'yellow',
        qualityStatus: 'green',
        overallStatus: 'green',
        statusExplanation: 'January focused on confirming the regional expansion approach and narrowing the first launch counties. Planning remains on track, though partner decision timelines need close monitoring.',
        accomplishments: [
          'Completed the priority-region screening and confirmed Skagit and one alternate county for early launch planning.',
          'Drafted the diversion operating model, intake flow, and partner engagement sequence for review with legal and operations.',
          'Established the expansion governance cadence with monthly leadership checkpoints and weekly launch-team working sessions.',
        ],
        commitments: [
          'Secure executive confirmation of the first launch county and alternate county by mid-February.',
          'Complete draft partner MOU language and begin agency review meetings.',
          'Finalize the staffing model and launch-readiness checklist for regional implementation.',
        ],
        milestoneChanges: 'No milestone date changes this month.',
        newRisks: [
          'County legal review timelines may slow execution of partner MOUs.',
          'Referral volume assumptions still need validation with prosecutors and courts.',
        ],
        decisionsNeeded: 'Confirm whether Skagit remains the primary launch county if legal review extends beyond the second week of February.',
        helpNeeded: 'Support from executive leadership is needed to unblock cross-agency discussions with county decision makers.',
        notes: 'Stakeholder response to the expansion concept is positive, but partners want more clarity on referral forecasting and reporting expectations.',
      },
      {
        id: 'AOI-2026.1.2-UPD-2026-02',
        month: '2026-02',
        createdAt: '2026-02-28',
        scopeStatus: 'green',
        scheduleStatus: 'yellow',
        costStatus: 'green',
        riskStatus: 'yellow',
        qualityStatus: 'green',
        overallStatus: 'yellow',
        statusExplanation: 'Partner alignment advanced in February, but one county approval path is taking longer than planned. The initiative is still viable, though the launch-readiness review needs tighter schedule management.',
        accomplishments: [
          'Held partner working sessions with court, prosecutor, and community provider representatives to validate the referral model.',
          'Completed the first draft of county MOUs and escalated legal comments requiring policy clarification.',
          'Built the launch staffing profile, onboarding sequence, and training approach for the first expansion region.',
        ],
        commitments: [
          'Resolve outstanding MOU language and secure final partner sign-off in March.',
          'Confirm staffing requisitions, interview plan, and onboarding owners for launch roles.',
          'Run a formal launch-readiness review against staffing, referral, reporting, and facilities criteria.',
        ],
        milestoneChanges: 'The partner MOU milestone remains in February, but execution may spill into early March if legal comments are not resolved in the next two weeks.',
        newRisks: [
          'Delayed county counsel review could compress training and go-live preparation.',
          'Unclear ownership for referral data reporting may create rework in launch dashboards.',
        ],
        decisionsNeeded: 'Approve a contingency path that allows training and staffing prep to continue before every MOU signature is complete.',
        helpNeeded: 'Need legal and data-governance support to close open questions on information sharing and reporting ownership.',
        notes: 'The team has enough clarity to keep moving, but schedule float is now limited and should be watched closely in March.',
      },
      {
        id: 'AOI-2026.1.2-UPD-2026-03',
        month: '2026-03',
        createdAt: '2026-03-31',
        scopeStatus: 'green',
        scheduleStatus: 'yellow',
        costStatus: 'green',
        riskStatus: 'yellow',
        qualityStatus: 'green',
        overallStatus: 'yellow',
        statusExplanation: 'March closed with the initiative largely launch-ready. Most dependencies are in place, but final hiring timing and one partner approval remain the main watch items before full go-live.',
        accomplishments: [
          'Completed the launch-readiness review and closed most open actions across staffing, facilities, and training.',
          'Finalized referral workflow documentation, intake scripts, and draft performance dashboards for regional launch teams.',
          'Aligned executive, operations, and partnerships leaders on the first-quarter post-launch stabilization approach.',
        ],
        commitments: [
          'Complete final hiring decisions and onboarding dates for launch staff in early April.',
          'Secure final signature from the remaining partner agency and lock the first referral activation date.',
          'Begin the first month of go-live support and issue management once launch criteria are met.',
        ],
        milestoneChanges: 'Launch readiness review completed on plan; final partner execution is being tracked as a watch item ahead of go-live.',
        newRisks: [
          'Recruitment timing for case-management roles could affect early service capacity.',
          'If partner signatures slip further, go-live sequencing may need to be phased by referral source.',
        ],
        decisionsNeeded: 'Confirm whether to proceed with phased go-live if one referral partner is delayed but all other launch criteria are met.',
        helpNeeded: 'Need recruiting support to accelerate finalist conversion for regional launch roles.',
        notes: 'This initiative now has a credible launch path and enough seeded detail for slide exports, dashboard review, and progress-update proof of concept.',
      },
    ],
  },
  {
    id: '2026.1.3',
    title: 'Strengthen and scale Pioneer\'s reentry service model',
    year: 2026,
    owner: 'Clint',
    strategicPriorityId: 'SP-201',
    strategicPriorityTitle: 'Create sustainable program impact',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Strengthen reentry programming and broaden adoption of the service model.',
    milestones: [
      {
        id: 'AOI-2026.1.3-MS-1',
        title: 'Reentry model baseline complete',
        description: 'Document current service delivery, performance gaps, and scaling priorities across the reentry model.',
        plannedDate: '2026-01-31',
        originalPlannedDate: '2026-01-31',
        actualDate: '2026-01-30',
      },
      {
        id: 'AOI-2026.1.3-MS-2',
        title: 'Standard service playbook drafted',
        description: 'Create a standardized operating playbook for reentry intake, service coordination, and partner handoffs.',
        plannedDate: '2026-02-28',
        originalPlannedDate: '2026-02-28',
        actualDate: '',
      },
      {
        id: 'AOI-2026.1.3-MS-3',
        title: 'Pilot scale-up package approved',
        description: 'Confirm readiness to pilot the strengthened reentry model in additional sites with clear measures and support plans.',
        plannedDate: '2026-03-31',
        originalPlannedDate: '2026-03-31',
        actualDate: '',
      },
    ],
    monthlyProgressUpdates: [
      {
        id: 'AOI-2026.1.3-UPD-2026-01',
        month: '2026-01',
        createdAt: '2026-01-31',
        scopeStatus: 'green',
        scheduleStatus: 'green',
        costStatus: 'green',
        riskStatus: 'green',
        qualityStatus: 'green',
        overallStatus: 'green',
        statusExplanation: 'January established a solid baseline for the reentry initiative. The team completed service-model discovery and identified the most important standardization gaps to address first.',
        accomplishments: [
          'Completed interviews with program leads and frontline staff to document the current-state reentry service model.',
          'Identified the highest-value opportunities to standardize client handoffs, case planning, and post-release follow-up.',
          'Defined the first draft of pilot success measures for service consistency, engagement, and partner coordination.',
        ],
        commitments: [
          'Draft the standard service playbook for intake, care coordination, and partner referrals.',
          'Confirm pilot sites and leadership sponsors for the first scale-up locations.',
          'Review current data capture gaps and define the minimum reporting requirements for the strengthened model.',
        ],
        milestoneChanges: 'No milestone date changes this month.',
        newRisks: [
          'Variation in site-level practice may make it harder to standardize the playbook quickly.',
        ],
        decisionsNeeded: 'Confirm whether the initial playbook should target all sites or focus on a smaller pilot cohort first.',
        helpNeeded: 'Need analytical support to compare performance and process variation across current reentry sites.',
        notes: 'The current-state assessment surfaced strong local practices that can be scaled, but adoption strategy will matter as much as the playbook content.',
      },
      {
        id: 'AOI-2026.1.3-UPD-2026-02',
        month: '2026-02',
        createdAt: '2026-02-28',
        scopeStatus: 'green',
        scheduleStatus: 'green',
        costStatus: 'green',
        riskStatus: 'yellow',
        qualityStatus: 'green',
        overallStatus: 'green',
        statusExplanation: 'February produced a usable draft playbook and narrowed the pilot design. The main watch item is ensuring sites have enough capacity and training support to adopt the model consistently.',
        accomplishments: [
          'Drafted the standard reentry playbook covering intake, case planning, care transitions, and partner escalation paths.',
          'Selected pilot sites and mapped the support needed for local leaders, frontline staff, and partner liaisons.',
          'Outlined a training and coaching approach to reinforce consistent use of the model during pilot rollout.',
        ],
        commitments: [
          'Validate the draft playbook with pilot-site teams and incorporate frontline feedback.',
          'Finalize reporting definitions and a lightweight quality-review cadence for the pilot period.',
          'Prepare the pilot scale-up package for March leadership review and approval.',
        ],
        milestoneChanges: 'The playbook milestone remains on track for completion in February.',
        newRisks: [
          'Pilot sites may need temporary backfill coverage to participate fully in training and coaching.',
          'Reporting definitions may need refinement before cross-site comparisons are reliable.',
        ],
        decisionsNeeded: 'Approve temporary staffing coverage for pilot sites to protect service delivery during training.',
        helpNeeded: 'Need PMO support to coordinate cross-site feedback, training logistics, and document version control.',
        notes: 'The content is strong enough to move forward, but pilot adoption support should be treated as a core workstream rather than a side activity.',
      },
      {
        id: 'AOI-2026.1.3-UPD-2026-03',
        month: '2026-03',
        createdAt: '2026-03-31',
        scopeStatus: 'green',
        scheduleStatus: 'yellow',
        costStatus: 'green',
        riskStatus: 'yellow',
        qualityStatus: 'green',
        overallStatus: 'yellow',
        statusExplanation: 'March closed with the pilot scale-up package nearly complete. Readiness is good overall, but adoption sequencing and reporting discipline still need attention before broader rollout begins.',
        accomplishments: [
          'Completed pilot-site validation sessions and incorporated operational feedback into the reentry service playbook.',
          'Built the pilot scorecard, quality-review approach, and escalation process for service delivery issues.',
          'Prepared the scale-up package, including adoption expectations, coaching model, and leadership checkpoints.',
        ],
        commitments: [
          'Obtain final leadership approval of the pilot scale-up package in early April.',
          'Launch pilot onboarding and coaching for participating sites.',
          'Begin monthly quality reviews and capture lessons for a second-wave rollout decision.',
        ],
        milestoneChanges: 'Approval of the pilot scale-up package is carrying into early April to align with leadership calendars.',
        newRisks: [
          'If pilot sites adopt the model at uneven speeds, cross-site outcome comparisons may be misleading in the first month.',
          'Leadership review timing could delay the formal pilot kickoff by one to two weeks.',
        ],
        decisionsNeeded: 'Confirm whether pilot success should be judged primarily on adoption consistency, client outcomes, or both in the first reporting cycle.',
        helpNeeded: 'Need sponsor support to keep pilot-site leaders engaged and accountable for training participation and reporting.',
        notes: 'This initiative now has complete seeded updates that work well for dashboard, detail-page, and export proof-of-concept scenarios.',
      },
    ],
  },
  {
    id: '2026.2.1',
    title: 'Ensure Pioneer can attract and retain the talent needed to support growth',
    year: 2026,
    owner: 'Debbie',
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Improve recruiting pipelines and retention practices to support planned growth.',
  },
  {
    id: '2026.2.2',
    title: 'Ensure the organization has the leadership capacity to sustain long-term growth',
    year: 2026,
    owner: 'Debbie',
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Build leadership depth and succession plans needed for long-term expansion.',
  },
  {
    id: '2026.2.3',
    title: 'Ensure equity is reflected in how Pioneer recruits, develops and advances talent',
    year: 2026,
    owner: 'Debbie',
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Advance equitable hiring, development, and promotion outcomes across the organization.',
  },
  {
    id: '2026.2.4',
    title: 'Shift HR capacity toward higher-value strategic work',
    year: 2026,
    owner: 'Debbie',
    strategicPriorityId: 'SP-202',
    strategicPriorityTitle: 'Prioritize employee well-being',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Reduce low-value HR work and shift capacity toward strategic workforce support.',
  },
  {
    id: '2026.3.1',
    title: 'Strengthen the scale and diversification of Pioneer Industries',
    year: 2026,
    owner: 'Alex',
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Grow and diversify Pioneer Industries through new customers, investments, and marketing.',
  },
  {
    id: '2026.3.2',
    title: 'Expand and diversify our food services enterprise',
    year: 2026,
    owner: 'VP Innovation',
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Expand food services offerings and define a sustainable path for future growth.',
  },
  {
    id: '2026.3.3',
    title: 'Strengthen financial sustainability across program operations',
    year: 2026,
    owner: 'Sandra',
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Improve revenue diversity and strengthen the financial model of program operations.',
  },
  {
    id: '2026.3.4',
    title: 'Optimize building assets to support mission and financial performance',
    year: 2026,
    owner: 'Sandra',
    strategicPriorityId: 'SP-203',
    strategicPriorityTitle: 'Build strong financial resilience',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Plan building and real-estate use to better support mission delivery and financial performance.',
  },
  {
    id: '2026.4.1',
    title: 'Identify and advance new mission-aligned enterprise opportunities',
    year: 2026,
    owner: 'VP Innovation',
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Identify and evaluate new enterprise opportunities that align with mission and capacity.',
  },
  {
    id: '2026.4.2',
    title: 'Establish a structured process for capturing and evaluating new ideas',
    year: 2026,
    owner: 'VP Innovation',
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Create a repeatable process for collecting, reviewing, and advancing new ideas.',
  },
  {
    id: '2026.4.3',
    title: 'Test a transitional jobs model in landscaping services',
    year: 2026,
    owner: 'VP Innovation',
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Pilot a landscaping-based transitional jobs model and assess expansion potential.',
  },
  {
    id: '2026.4.4',
    title: 'Strengthen technology infrastructure, security and collaboration across the organization',
    year: 2026,
    owner: 'Diana',
    strategicPriorityId: 'SP-204',
    strategicPriorityTitle: 'Build a supportive ecosystem that fosters innovation',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Upgrade core technology, security, and collaboration capabilities across the organization.',
  },
  {
    id: '2026.5.1',
    title: 'Expand housing access for justice-involved individuals',
    year: 2026,
    owner: 'Hilary',
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Advance fair chance housing efforts for justice-involved individuals through advocacy and partnership.',
  },
  {
    id: '2026.5.2',
    title: 'Ensure continuity of healthcare coverage for justice-involved populations',
    year: 2026,
    owner: 'Hilary',
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Protect continuity of healthcare coverage for justice-involved populations.',
  },
  {
    id: '2026.5.3',
    title: 'Advance policy reforms that reduce unnecessary incarceration',
    year: 2026,
    owner: 'Hilary',
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Develop reforms that reduce unnecessary incarceration and support system change.',
  },
  {
    id: '2026.5.4',
    title: 'Elevate visibility of Pioneer\'s impact',
    year: 2026,
    owner: 'Hilary',
    strategicPriorityId: 'SP-205',
    strategicPriorityTitle: 'Champion systemic changes within the criminal justice system',
    strategicPriorityPeriodId: 'SPP-2024-2029',
    strategicPriorityPeriodLabel: 'Strategic Priorities 2024-2029',
    description: 'Increase visibility of Pioneer’s outcomes and impact through reporting and outreach.',
  },
];

export const SEEDED_STRATEGIC_PRIORITY_PERIODS = [
  {
    id: 'SPP-2024-2029',
    label: 'Strategic Priorities 2024-2029',
    approvedOn: '2026-04-12',
    startYear: 2024,
    endYear: 2029,
    status: 'active',
    priorities: [
      {
        id: 'SP-201',
        title: 'Create sustainable program impact',
        description: '',
      },
      {
        id: 'SP-202',
        title: 'Prioritize employee well-being',
        description: '',
      },
      {
        id: 'SP-203',
        title: 'Build strong financial resilience',
        description: '',
      },
      {
        id: 'SP-204',
        title: 'Build a supportive ecosystem that fosters innovation',
        description: '',
      },
      {
        id: 'SP-205',
        title: 'Champion systemic changes within the criminal justice system',
        description: '',
      },
    ],
  },
];
